name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1' # Weekly at Monday midnight

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          # Ensure clean git state
          git fetch --unshallow || true
          
          # Get short SHA for tagging
          SHA=$(git rev-parse --short HEAD)
          
          for dir in */; do
            # Skip if no Dockerfile exists
            [ -f "$dir/Dockerfile" ] || continue
            
            dir_name=$(basename "$dir")
            image_name="${DOCKER_USERNAME}/${dir_name}"
            tag_latest="${image_name}:latest"
            tag_sha="${image_name}:${SHA}"
            
            echo "Building and pushing image for $dir_name"
            
            # Build and push with multiple tags
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --tag "$tag_latest" \
              --tag "$tag_sha" \
              --push \
              "$dir"
            
            echo "Pushed $tag_latest and $tag_sha"
          done
