name: Build and Push Docker Images for Each Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '55 0 * * 1'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images for Each Directory
        run: |
          for dir in $(ls -d */); do
            dir_name=$(basename $dir)
            tag_name="username/${dir_name}:latest-$(date +'%Y%m%d%H%M')"
            echo "Building and pushing image for $dir_name with tag $tag_name"
            docker build -t $tag_name ./$dir_name
            docker push $tag_name
          done
